//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteNested2.Models
{
  using System;
  using System.Collections.Generic;

  public partial class Employee
  {
    public Employee()
    {
      this.Phone = new HashSet<Phone>();
    }

    public long EmployeeID { get; set; }
    public string Name { get; set; }
    public string Salary { get; set; }

    public virtual ICollection<Phone> Phone { get; set; }

    internal void CreatePhoneNumber(int count = 1)
    {
      for (int i = 0; i < count; i++)
        Phone.Add(new Phone());
    }
  }
}
